import { Card, OpponentCard } from '../types';

export const PLAYER_CARDS: Card[] = [
  // --- Group 1: Dice Geometry (10) ---
  {
    id: 'card_overclock',
    name: 'OVERCLOCK',
    tagline: 'Dice Geometry',
    description: 'Increases the lower die by +1 on non-natural double rolls (Max 6).',
    category: 'self',
    rarity: 'common',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'Zap',
    effectKey: 'OVERCLOCK',
  },
  {
    id: 'card_synchronize',
    name: 'SYNCHRONIZE',
    tagline: 'Dice Geometry',
    description: 'If non-double dice are consecutive, lower die increases by +1 (e.g., 5-4 → 5-5). Only 2 moves played.',
    category: 'self',
    rarity: 'common',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'GitMerge',
    effectKey: 'SYNCHRONIZE',
  },
  {
    id: 'card_convergence',
    name: 'CONVERGENCE',
    tagline: 'Dice Geometry',
    description: 'If non-double dice differ by at least 3, lower die gets +2 and higher die gets −1 (e.g., 6-1 → 5-3).',
    category: 'self',
    rarity: 'rare',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'Minimize2',
    effectKey: 'CONVERGENCE',
  },
  {
    id: 'card_cold_reboot',
    name: 'COLD REBOOT',
    tagline: 'Dice Geometry',
    description: 'If raw dice sum is 5 or lower, optionally reroll both dice once.',
    category: 'self',
    rarity: 'rare',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'RotateCcw',
    effectKey: 'COLD_REBOOT',
  },
  {
    id: 'card_double_tuner',
    name: 'DOUBLE TUNER',
    tagline: 'Dice Geometry',
    description: 'On natural double x-x, replaces 4 identical values with [x−1, x, x, x+1].',
    category: 'self',
    rarity: 'epic',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'Sliders',
    effectKey: 'DOUBLE_TUNER',
  },
  {
    id: 'card_doubles_engine',
    name: 'DOUBLES ENGINE',
    tagline: 'Dice Geometry',
    description: 'On natural doubles, allows using the die value 5 times instead of 4.',
    category: 'self',
    rarity: 'legendary',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'Sparkles',
    effectKey: 'DOUBLES_ENGINE',
  },
  {
    id: 'card_compression_field',
    name: 'COMPRESSION FIELD',
    tagline: 'Dice Geometry',
    description: 'If opponent non-double dice differ by at least 3, higher die gets −2, lower die gets +1 (e.g., 6-1 → 4-2).',
    category: 'sabotage',
    rarity: 'epic',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'Disc',
    effectKey: 'COMPRESSION_FIELD',
  },
  {
    id: 'card_overvoltage_trip',
    name: 'OVERVOLTAGE TRIP',
    tagline: 'Dice Geometry',
    description: 'If opponent non-double dice sum is 10 or higher, forces opponent dice to automatically reroll.',
    category: 'sabotage',
    rarity: 'epic',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'AlertTriangle',
    effectKey: 'OVERVOLTAGE_TRIP',
  },
  {
    id: 'card_double_fault',
    name: 'DOUBLE FAULT',
    tagline: 'Dice Geometry',
    description: 'When opponent rolls a natural double, grants them only 3 moves instead of 4.',
    category: 'sabotage',
    rarity: 'rare',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'MinusCircle',
    effectKey: 'DOUBLE_FAULT',
  },
  {
    id: 'card_six_tax',
    name: 'SIX TAX',
    tagline: 'Dice Geometry',
    description: 'When opponent rolls a 6 on a non-double roll, their other die gets −1 (Min 1).',
    category: 'sabotage',
    rarity: 'common',
    type: 'dice',
    trigger: 'ON_DICE_ROLL',
    iconName: 'ShieldAlert',
    effectKey: 'SIX_TAX',
  },

  // --- Group 2: Blot & Hit (12) ---
  {
    id: 'card_mirror_reflex',
    name: 'MIRROR REFLEX',
    tagline: 'Blot & Hit',
    description: 'When your blot is hit, the hitting opponent checker is also sent to the Bar.',
    category: 'self',
    rarity: 'rare',
    type: 'hit',
    trigger: 'ON_HIT_OPPONENT',
    iconName: 'ShieldAlert',
    effectKey: 'MIRROR_REFLEX',
  },
  {
    id: 'card_shatter_blot',
    name: 'SHATTER BLOT',
    tagline: 'Blot & Hit',
    description: 'When you hit an opponent blot, an adjacent opponent blot directly ahead also gets sent to the Bar.',
    category: 'self',
    rarity: 'rare',
    type: 'hit',
    trigger: 'ON_HIT_OPPONENT',
    iconName: 'Zap',
    effectKey: 'SHATTER_BLOT',
  },
  {
    id: 'card_double_tap',
    name: 'DOUBLE TAP',
    tagline: 'Blot & Hit',
    description: 'After your first hit in a turn, any unused die gets +1 (Max 6).',
    category: 'self',
    rarity: 'epic',
    type: 'hit',
    trigger: 'ON_HIT_OPPONENT',
    iconName: 'Target',
    effectKey: 'DOUBLE_TAP',
  },
  {
    id: 'card_open_circuit',
    name: 'OPEN CIRCUIT',
    tagline: 'Blot & Hit',
    description: 'If you end your turn with at least one open blot, your lower die gets +1 on your next non-double roll.',
    category: 'self',
    rarity: 'common',
    type: 'dice',
    trigger: 'PASSIVE',
    iconName: 'Activity',
    effectKey: 'OPEN_CIRCUIT',
  },
  {
    id: 'card_second_wind',
    name: 'SECOND WIND',
    tagline: 'Blot & Hit',
    description: 'When one of your blots is hit, your lower die gets +1 on your next turn (Max 6).',
    category: 'self',
    rarity: 'rare',
    type: 'dice',
    trigger: 'PASSIVE',
    iconName: 'Wind',
    effectKey: 'SECOND_WIND',
  },
  {
    id: 'card_deflection',
    name: 'DEFLECTION',
    tagline: 'Blot & Hit',
    description: 'When your blot is hit, instead of going to the Bar, it retreats 1 point backward if possible.',
    category: 'self',
    rarity: 'epic',
    type: 'hit',
    trigger: 'PASSIVE',
    iconName: 'CornerUpLeft',
    effectKey: 'DEFLECTION',
  },
  {
    id: 'card_compulsory_hit',
    name: 'COMPULSORY HIT',
    tagline: 'Blot & Hit',
    description: 'If opponent has any legal move sequence containing a hit, they MUST perform at least one hit.',
    category: 'sabotage',
    rarity: 'epic',
    type: 'hit',
    trigger: 'PASSIVE',
    iconName: 'Flame',
    effectKey: 'COMPULSORY_HIT',
  },
  {
    id: 'card_blood_tax',
    name: 'BLOOD TAX',
    tagline: 'Blot & Hit',
    description: 'After opponent makes their first hit in a turn, their next die gets −1 (Min 1).',
    category: 'sabotage',
    rarity: 'rare',
    type: 'hit',
    trigger: 'ON_HIT_OPPONENT',
    iconName: 'Droplet',
    effectKey: 'BLOOD_TAX',
  },
  {
    id: 'card_double_fracture',
    name: 'DOUBLE FRACTURE',
    tagline: 'Blot & Hit',
    description: 'When opponent makes a hit during a double roll, 1 remaining die move is destroyed.',
    category: 'sabotage',
    rarity: 'epic',
    type: 'hit',
    trigger: 'ON_HIT_OPPONENT',
    iconName: 'Scissors',
    effectKey: 'DOUBLE_FRACTURE',
  },
  {
    id: 'card_backlash',
    name: 'BACKLASH',
    tagline: 'Blot & Hit',
    description: 'After opponent makes their first hit in a turn, the hitting checker retreats 1 point backward if possible.',
    category: 'sabotage',
    rarity: 'rare',
    type: 'hit',
    trigger: 'ON_HIT_OPPONENT',
    iconName: 'Undo',
    effectKey: 'BACKLASH',
  },
  {
    id: 'card_blood_magnet',
    name: 'BLOOD MAGNET',
    tagline: 'Blot & Hit',
    description: 'If opponent starts their turn with at least one blot and has valid moves, their first move MUST move a blot.',
    category: 'sabotage',
    rarity: 'rare',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Magnet',
    effectKey: 'BLOOD_MAGNET',
  },
  {
    id: 'card_cowards_tax',
    name: 'COWARD\'S TAX',
    tagline: 'Blot & Hit',
    description: 'If opponent has at least one legal hit opportunity during their turn but chooses not to hit, their lower die gets −1 on their next turn.',
    category: 'sabotage',
    rarity: 'common',
    type: 'dice',
    trigger: 'PASSIVE',
    iconName: 'EyeOff',
    effectKey: 'COWARDS_TAX',
  },

  // --- Group 3: Gates & Board Control (2) ---
  {
    id: 'card_magnetic_link',
    name: 'MAGNETIC LINK',
    tagline: 'Gates & Control',
    description: 'If a move ends exactly 1 point behind your own blot, it automatically advances +1 to form a point/gate.',
    category: 'self',
    rarity: 'epic',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Link',
    effectKey: 'MAGNETIC_LINK',
  },
  {
    id: 'card_repulsor',
    name: 'REPULSOR',
    tagline: 'Gates & Control',
    description: 'If opponent moves onto their own blot to form a new point, the landing checker is pushed +1 forward, preventing point creation.',
    category: 'sabotage',
    rarity: 'epic',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Radio',
    effectKey: 'REPULSOR',
  },

  // --- Group 4: Bar & Re-entry (6) ---
  {
    id: 'card_counterstrike',
    name: 'COUNTERSTRIKE',
    tagline: 'Bar & Re-entry',
    description: 'When re-entering from the Bar and hitting an opponent blot, any unused die gets +1 (Max 6).',
    category: 'self',
    rarity: 'rare',
    type: 'bar',
    trigger: 'ON_RE_ENTER_BAR',
    iconName: 'Crosshair',
    effectKey: 'COUNTERSTRIKE',
  },
  {
    id: 'card_launchpad',
    name: 'LAUNCHPAD',
    tagline: 'Bar & Re-entry',
    description: 'When re-entering from the Bar onto your own blot to form a point, any unused die gets +1 (Max 6).',
    category: 'self',
    rarity: 'rare',
    type: 'bar',
    trigger: 'ON_RE_ENTER_BAR',
    iconName: 'Rocket',
    effectKey: 'LAUNCHPAD',
  },
  {
    id: 'card_failsafe',
    name: 'FAILSAFE',
    tagline: 'Bar & Re-entry',
    description: 'If you cannot re-enter any checker from the Bar for an entire turn, your lower die gets +1 on your next turn.',
    category: 'self',
    rarity: 'common',
    type: 'bar',
    trigger: 'PASSIVE',
    iconName: 'ShieldCheck',
    effectKey: 'FAILSAFE',
  },
  {
    id: 'card_batch_upload',
    name: 'BATCH UPLOAD',
    tagline: 'Bar & Re-entry',
    description: 'If you start your turn with exactly 2 checkers on the Bar and roll a non-double with valid entry, both checkers re-enter together using 1 die.',
    category: 'self',
    rarity: 'legendary',
    type: 'bar',
    trigger: 'ON_RE_ENTER_BAR',
    iconName: 'UploadCloud',
    effectKey: 'BATCH_UPLOAD',
  },
  {
    id: 'card_bypass_protocol',
    name: 'BYPASS PROTOCOL',
    tagline: 'Bar & Re-entry',
    description: 'If you have checkers on the Bar but your dice cannot re-enter them, Bar priority is suspended and you may move checkers on the board.',
    category: 'self',
    rarity: 'legendary',
    type: 'bar',
    trigger: 'PASSIVE',
    iconName: 'Unlock',
    effectKey: 'BYPASS_PROTOCOL',
  },
  {
    id: 'card_bar_static',
    name: 'BAR STATIC',
    tagline: 'Bar & Re-entry',
    description: 'If opponent starts their turn with 2 or more checkers on the Bar, their higher die gets −1 before resolving entries.',
    category: 'sabotage',
    rarity: 'rare',
    type: 'bar',
    trigger: 'PASSIVE',
    iconName: 'WifiOff',
    effectKey: 'BAR_STATIC',
  },

  // --- Group 5: Board Anomaly (1) ---
  {
    id: 'card_black_ice',
    name: 'BLACK ICE',
    tagline: 'Board Anomaly',
    description: 'If an opponent checker ends its move on the icy point designated at match start, it is instantly sent to the Bar.',
    category: 'sabotage',
    rarity: 'epic',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Snowflake',
    effectKey: 'BLACK_ICE',
  },

  // --- Group 6: Movement & Dead Rolls (4) ---
  {
    id: 'card_packet_drop',
    name: 'PACKET DROP',
    tagline: 'Movement & Dead Rolls',
    description: 'After playing 1 die on a non-double roll, you may discard the remaining die and end your turn.',
    category: 'self',
    rarity: 'common',
    type: 'movement',
    trigger: 'ACTIVE_ABILITY',
    iconName: 'Trash2',
    effectKey: 'PACKET_DROP',
  },
  {
    id: 'card_lost_packet',
    name: 'LOST PACKET',
    tagline: 'Movement & Dead Rolls',
    description: 'If opponent cannot play one of their dice and ends turn early, their lower die gets −1 on their next turn.',
    category: 'sabotage',
    rarity: 'common',
    type: 'dice',
    trigger: 'PASSIVE',
    iconName: 'PackageX',
    effectKey: 'LOST_PACKET',
  },
  {
    id: 'card_echo_jam',
    name: 'ECHO JAM',
    tagline: 'Movement & Dead Rolls',
    description: 'If opponent uses both dice on the same checker on a non-double turn, the second die gets −1 (Min 1).',
    category: 'sabotage',
    rarity: 'rare',
    type: 'dice',
    trigger: 'PASSIVE',
    iconName: 'Repeat',
    effectKey: 'ECHO_JAM',
  },
  {
    id: 'card_forced_commit',
    name: 'FORCED COMMIT',
    tagline: 'Movement & Dead Rolls',
    description: 'If opponent plays their first die on a checker and the second die can also be played on the same checker, they MUST play it on the same checker.',
    category: 'sabotage',
    rarity: 'rare',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Lock',
    effectKey: 'FORCED_COMMIT',
  },

  // --- Group 7: Home & Bear Off (4) ---
  {
    id: 'card_redundancy',
    name: 'REDUNDANCY',
    tagline: 'Home & Bear Off',
    description: 'When all checkers are in your home board and one die cannot be played at all, the playable die can be used twice.',
    category: 'self',
    rarity: 'rare',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'CopyPlus',
    effectKey: 'REDUNDANCY',
  },
  {
    id: 'card_home_security',
    name: 'HOME SECURITY',
    tagline: 'Home & Bear Off',
    description: 'If opponent has at least one open blot in their home board, they cannot bear off checkers.',
    category: 'sabotage',
    rarity: 'epic',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'ShieldAlert',
    effectKey: 'HOME_SECURITY',
  },
  {
    id: 'card_final_check',
    name: 'FINAL CHECK',
    tagline: 'Home & Bear Off',
    description: 'Opponent cannot bear off their last remaining checker with overshoot (excess die). Must be an exact die roll.',
    category: 'sabotage',
    rarity: 'rare',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'CheckSquare',
    effectKey: 'FINAL_CHECK',
  },
  {
    id: 'card_exact_lock',
    name: 'EXACT LOCK',
    tagline: 'Home & Bear Off',
    description: 'Opponent cannot bear off any checkers with overshoot. Checkers can only be borne off on exact die matches.',
    category: 'sabotage',
    rarity: 'epic',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Key',
    effectKey: 'EXACT_LOCK',
  },

  // --- Group 8: Race & Pip (2) ---
  {
    id: 'card_tailwind',
    name: 'TAILWIND',
    tagline: 'Race & Pip',
    description: 'The first time you move your rearmost checker each turn, the die used gets +1 (Max 6).',
    category: 'self',
    rarity: 'common',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'FastForward',
    effectKey: 'TAILWIND',
  },
  {
    id: 'card_trailing_drag',
    name: 'TRAILING DRAG',
    tagline: 'Race & Pip',
    description: 'The first time opponent moves their rearmost checker each turn, the die used gets −1 (Min 1).',
    category: 'sabotage',
    rarity: 'common',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Rewind',
    effectKey: 'TRAILING_DRAG',
  },

  // --- Group 9: Marked Checkers (2) ---
  {
    id: 'card_courier',
    name: 'COURIER',
    tagline: 'Marked Checkers',
    description: 'Your Courier checker designated at match start gets +1 die distance every time it moves (Max 6).',
    category: 'self',
    rarity: 'rare',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Navigation',
    effectKey: 'COURIER',
  },
  {
    id: 'card_deadweight',
    name: 'DEADWEIGHT',
    tagline: 'Marked Checkers',
    description: 'The opponent Deadweight checker designated at match start gets −1 die distance every time it moves (Min 1).',
    category: 'sabotage',
    rarity: 'rare',
    type: 'movement',
    trigger: 'PASSIVE',
    iconName: 'Anchor',
    effectKey: 'DEADWEIGHT',
  },

  // --- Group 9: Campaign Legendary Rewards (won from protocol bosses, never in the random pools) ---
  {
    id: 'card_event_horizon',
    name: 'EVENT HORIZON',
    tagline: 'Gravity Well',
    description: 'Every time the opponent bears off a checker, their next roll\'s lower die gets −1 (Min 1) — gravity intensifies the closer they get to escaping.',
    category: 'sabotage',
    rarity: 'legendary',
    type: 'bar',
    trigger: 'ON_BEAR_OFF',
    iconName: 'Orbit',
    effectKey: 'EVENT_HORIZON',
  },
  {
    id: 'card_termination_protocol',
    name: 'TERMINATION PROTOCOL',
    tagline: 'Full Lockdown',
    description: 'OMEGA CORE\'s own blots can never be hit — its exposed checkers cannot be broken.',
    category: 'sabotage',
    rarity: 'legendary',
    type: 'bar',
    trigger: 'PASSIVE',
    iconName: 'Skull',
    effectKey: 'TERMINATION_PROTOCOL',
    // OMEGA CORE's signature card — the final boss only. Never appears in the shared 1v1
    // quick-match draft pool (see handleStartQuickMatch), so it can be this punishing.
    exclusiveToBoss: 'boss_omega_core',
  }
];

export const OPPONENT_BOSSES: OpponentCard[] = [
  {
    id: 'boss_glitch_bot',
    bossName: 'GLITCH-9',
    bossTitle: 'Sub-Zero Rogue AI',
    avatarSeed: 'glitch',
    accentColor: '#00f0ff',
    quote: 'Your code is full of flaws. Let me corrupt your rolls.',
    difficulty: 1,
    signatureCardId: 'card_six_tax',
  },
  {
    id: 'boss_cyber_phantom',
    bossName: 'PHANTOM.EXE',
    bossTitle: 'Spectral Cyber Ninja',
    avatarSeed: 'phantom',
    accentColor: '#ff007f',
    quote: 'Now you see me... now your checkers disappear.',
    difficulty: 2,
    signatureCardId: 'card_black_ice',
  },
  {
    id: 'boss_vector_vampire',
    bossName: 'VEC-TOR 3000',
    bossTitle: 'Vampiric Code Executioner',
    avatarSeed: 'vector',
    accentColor: '#a855f7',
    quote: 'Your pip count nourishes my grid processing power.',
    difficulty: 3,
    signatureCardId: 'card_blood_tax',
  },
  {
    id: 'boss_matrix_architect',
    bossName: 'THE ARCHITECT',
    bossTitle: 'Probability Manipulator',
    avatarSeed: 'architect',
    accentColor: '#22c55e',
    quote: 'Probability is an illusion. I have dictated the die outcomes.',
    difficulty: 4,
    signatureCardId: 'card_compression_field',
  },
  {
    id: 'boss_gravity_synth',
    bossName: 'SINGULARITY',
    bossTitle: 'Gravitational Core',
    avatarSeed: 'singularity',
    accentColor: '#eab308',
    quote: 'Space bends to my will. You cannot escape my event horizon.',
    difficulty: 5,
    signatureCardId: 'card_event_horizon',
  },
  {
    id: 'boss_omega_core',
    bossName: 'OMEGA CORE',
    bossTitle: 'Final Cyber God AI',
    avatarSeed: 'omega',
    accentColor: '#ef4444',
    quote: 'I AM NEXTGAMMON. ALL PATHS TERMINATE HERE.',
    difficulty: 6,
    signatureCardId: 'card_termination_protocol',
  }
];

